# Generated by Django 4.1.1 on 2022-09-28 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('action_time', models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 18, 45, 646344, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('SUB', 'Subscribed'), ('UNS', 'unsubscribed')], default='SUB', max_length=3)),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
        migrations.AddIndex(
            model_name='leads',
            index=models.Index(fields=['-action_time'], name='unity_leads_action__e2beca_idx'),
        ),
    ]
