# Generated by Django 4.1.1 on 2022-09-28 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
