# Generated by Django 4.1.1 on 2022-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0002_alter_leads_action_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=500)),
            ],
        ),
    ]
