# Generated by Django 4.1.1 on 2022-09-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unity.store'),
            preserve_default=False,
        ),
    ]
