# Generated by Django 4.1.1 on 2022-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0004_leads_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
